import os
import shutil
import uuid
from fastapi import FastAPI, UploadFile, File, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from dotenv import load_dotenv

# LangChain message modules test
from langchain_core.messages import HumanMessage

# Import our custom RAG and Graph Workflow builders
from app.graph.workflow import create_workflow
from app.rag.loader import load_pdf
from app.rag.splitter import split_documents
from app.rag.vectorstore import add_documents_to_store

# Auth dependencies
from app.auth.middleware import get_current_user

# Custom MongoDB checkpointer
from app.graph.checkpointer import AsyncMongoDBSaver
from motor.motor_asyncio import AsyncIOMotorClient

# 1. Initialize environment variables
load_dotenv()

# 2. Compile our LangGraph state machine with MongoDBSaver
mongo_client = AsyncIOMotorClient(os.getenv("MONGODB_URI"))
mongodb_saver = AsyncMongoDBSaver(mongo_client)
graph_app = create_workflow(checkpointer=mongodb_saver)

# 3. Initialize FastAPI
app = FastAPI(title="🏢 AI Operations Command Center")

# 3b. CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 3c. Register Auth Routes
from app.auth.routes import router as auth_router
app.include_router(auth_router)

# 3d. Register Business APIs
from app.api.dashboard import router as dashboard_router
from app.api.customers import router as customers_router
from app.api.finance import router as finance_router
from app.api.sales import router as sales_router
from app.api.support import router as support_router
from app.api.operations import router as ops_router
from app.api.hr import router as hr_router
from app.api.ai_command import router as ai_router
from app.api.chats import router as chats_router
from app.api.approvals import router as approvals_router

app.include_router(dashboard_router)
app.include_router(customers_router)
app.include_router(finance_router)
app.include_router(sales_router)
app.include_router(support_router)
app.include_router(ops_router)
app.include_router(hr_router)
app.include_router(ai_router)
app.include_router(chats_router)
app.include_router(approvals_router)

# 5. Serve Static UI Assets
app.mount("/static", StaticFiles(directory="app/static"), name="static")

# 6. Serving HTML Front-end UI at the root "/"
@app.get("/", response_class=HTMLResponse)
async def get_index():
    index_path = os.path.join("app", "static", "index.html")
    if not os.path.exists(index_path):
        raise HTTPException(status_code=404, detail="Index HTML not found.")
    with open(index_path, "r", encoding="utf-8") as f:
        return HTMLResponse(content=f.read())

# 7. Request schema for chat
class ChatRequest(BaseModel):
    query: str
    thread_id: str = None

# 8. API Endpoint: Send Chat Message
@app.post("/api/chat")
async def chat_endpoint(req: ChatRequest, user: dict = Depends(get_current_user)):
    try:
        query_text = req.query.strip()
        if not query_text:
            raise HTTPException(status_code=400, detail="Query cannot be empty.")

        # Secure isolation: thread_id is scoped to the authenticated user ID.
        # This acts as an implicit thread ownership verification.
        base_thread_id = req.thread_id if req.thread_id else str(uuid.uuid4())
        secure_thread_id = f"{user['user_id']}::{base_thread_id}"
        config = {"configurable": {"thread_id": secure_thread_id}}
        
        steps = []
        
        # Run workflow
        input_state = {"messages": [HumanMessage(content=query_text)]}
        async for event in graph_app.astream(input_state, config=config, stream_mode="updates"):
            for node_name, node_update in event.items():
                if node_name == "retrieve":
                    doc_count = len(node_update.get("context", []))
                    steps.append(f"RAG: Retrieved {doc_count} document chunks from Chroma DB.")
                elif node_name == "tools":
                    steps.append("Tools: Executed tools.")
                elif node_name == "agent":
                    steps.append("LLM: Agent generated response reasoning step.")

        # Retrieve the final consolidated state from the checkpointer
        final_state = await graph_app.aget_state(config)
        final_messages = final_state.values.get("messages", [])
        
        if not final_messages:
            raise HTTPException(status_code=500, detail="No response generated by the agent.")
            
        raw_content = final_messages[-1].content
        if isinstance(raw_content, list):
            final_response = "".join([part.get("text", "") for part in raw_content if isinstance(part, dict) and "text" in part])
        else:
            final_response = str(raw_content)
        
        return {
            "status": "success",
            "response": final_response,
            "steps": steps,
            "thread_id": base_thread_id
        }
        
    except HTTPException:
        raise
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

# 9. API Endpoint: Ingest & Upload PDF for RAG
@app.post("/api/upload")
async def upload_endpoint(file: UploadFile = File(...), user: dict = Depends(get_current_user)):
    try:
        if not file.filename.endswith(".pdf"):
            raise HTTPException(status_code=400, detail="Only PDF files are supported.")
            
        os.makedirs("data", exist_ok=True)
        file_path = os.path.join("data", file.filename)
        
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        raw_docs = load_pdf(file_path)
        split_docs = split_documents(raw_docs)
        add_documents_to_store(split_docs)
        
        return {
            "status": "success",
            "filename": file.filename,
            "chunks": len(split_docs)
        }
        
    except HTTPException:
        raise
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

class ClearRequest(BaseModel):
    thread_id: str = None

# 10. API Endpoint: Reset Chat Thread (Clear History)
@app.post("/api/clear")
async def clear_endpoint(req: ClearRequest = None, user: dict = Depends(get_current_user)):
    # Because the checkpoint is now persistent in MongoDB, we could manually delete the documents 
    # from the 'checkpoints' and 'checkpoints_writes' collections here, but a cleaner 
    # approach is to just let the client start fresh with a new thread_id.
    return {"status": "success", "message": "Conversation history cleared."}
