from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, ToolMessage, HumanMessage
from app.mcp.client import mcp_client
from app.models.llm import create_model
from app.graph.agents import AGENT_PROMPTS, SUPERVISOR_PROMPT

class RouterDecision(BaseModel):
    destination: str = Field(
        description="The exact name of the agent to route to (e.g., 'finance_agent', 'sales_agent', 'support_agent', 'operations_agent', 'hr_agent', 'knowledge_agent', 'executive_agent', 'general_agent'), or 'FINISH' if the task is fully complete."
    )

async def supervisor_node(state) -> dict:
    """
    The AI COO. Analyzes the current conversation and decides which specialized agent
    should execute next, or if the process should terminate.
    """
    messages = state["messages"]
    print("\n[AI COO] Analyzing request and planning delegation...")
    
    # We use a structured model to force the output to be exactly our schema
    classifier_model = create_model().with_structured_output(RouterDecision)
    
    # Build prompt for the supervisor
    full_messages = [SystemMessage(content=SUPERVISOR_PROMPT)] + list(messages)
    
    try:
        decision = await classifier_model.ainvoke(full_messages)
        next_agent = decision.destination
        print(f"[AI COO] Delegating task to: {next_agent}")
    except Exception as e:
        print(f"[AI COO Error] Routing failed. Defaulting to FINISH. Details: {str(e)}")
        next_agent = "FINISH"
        from langchain_core.messages import AIMessage
        return {"next_agent": next_agent, "messages": [AIMessage(content=f"AI COO Error: {str(e)}")]}
        
    return {"next_agent": next_agent}

async def worker_node(state) -> dict:
    """
    A dynamic worker node that loads the persona of the 'next_agent' specified by the supervisor.
    """
    messages = state["messages"]
    agent_name = state.get("next_agent", "FINISH")
    
    # If for some reason we are here but agent is FINISH, just do nothing
    if agent_name not in AGENT_PROMPTS:
        return {}
        
    print(f"\n[{agent_name.upper()}] Processing task...")
    
    # Load the specific system prompt for this agent
    system_text = AGENT_PROMPTS[agent_name]
    
    # Build full prompt
    full_messages = [SystemMessage(content=system_text)] + list(messages)
    
    # Connect to the MCP Server, fetch tools, bind to model, and invoke
    mcp_tools = await mcp_client.get_tools()
    model_with_tools = create_model(tools=mcp_tools)
    
    try:
        response = await model_with_tools.ainvoke(full_messages)
        return {"messages": [response]}
    except Exception as e:
        print(f"[Worker Error] Execution failed: {str(e)}")
        from langchain_core.messages import AIMessage
        return {"messages": [AIMessage(content=f"Worker Error ({agent_name}): {str(e)}")]}

def should_continue(state) -> str:
    """
    Decides if the worker node should transition to the tool node, or return to the supervisor.
    """
    messages = state["messages"]
    last_message = messages[-1]
    
    # If the LLM returned tool calls, go to the tools node
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        print(f"\n[Worker] LLM requested {len(last_message.tool_calls)} tool call(s). Routing to tools node...")
        return "tools"
    
    # Otherwise, the worker has provided a final answer to the user.
    return "end"

def supervisor_router(state) -> str:
    """
    Reads the supervisor's decision to route to the worker node or end.
    """
    agent = state.get("next_agent", "FINISH")
    if agent == "FINISH":
        return "end"
    return "worker"

async def tools_node(state) -> dict:
    """
    Executes tool calls generated by the worker agents against the MCP server.
    """
    messages = state["messages"]
    last_message = messages[-1]
    
    tool_messages = []
    
    # Fetch tools from the MCP Server to execute them
    mcp_tools = await mcp_client.get_tools()
    mcp_tools_map = {tool.name: tool for tool in mcp_tools}
    
    for tool_call in last_message.tool_calls:
        tool_name = tool_call["name"]
        tool_args = tool_call["args"]
        tool_id = tool_call["id"]
        
        print(f"\n[MCP Tools] Executing: {tool_name} with arguments: {tool_args}...")
        
        if tool_name in mcp_tools_map:
            tool_obj = mcp_tools_map[tool_name]
            try:
                result = await tool_obj.ainvoke(tool_args)
                print(f"[MCP Tools] {tool_name} returned: {result}")
            except Exception as e:
                result = f"Error executing tool: {str(e)}"
                print(f"[MCP Tools Error] {result}")
        else:
            result = f"Error: Tool '{tool_name}' not found on MCP Server."
            print(f"[MCP Tools Error] {result}")
            
        # Create the matching ToolMessage response
        tool_messages.append(
            ToolMessage(content=str(result), tool_call_id=tool_id)
        )
        
    return {"messages": tool_messages}
