import logging
import asyncio
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, ToolMessage, HumanMessage
from app.mcp.client import mcp_client
from app.models.llm import create_model
from app.graph.agents import AGENT_PROMPTS, SUPERVISOR_PROMPT

logger = logging.getLogger(__name__)

class RouterDecision(BaseModel):
    destination: str = Field(
        description="The exact name of the agent to route to, or 'FINISH' if the task is fully complete."
    )

async def supervisor_node(state) -> dict:
    """
    The AI COO. Analyzes the current conversation and decides which specialized agent
    should execute next, or if the process should terminate.
    """
    messages = state["messages"]
    logger.info("Analyzing request and planning delegation...")
    
    classifier_model = create_model().with_structured_output(RouterDecision)
    full_messages = [SystemMessage(content=SUPERVISOR_PROMPT)] + list(messages)
    
    try:
        decision = await classifier_model.ainvoke(full_messages)
        next_agent = decision.destination
        logger.info(f"Delegating task to: {next_agent}")
    except Exception as e:
        logger.error(f"Routing failed. Defaulting to FINISH. Details: {str(e)}")
        next_agent = "FINISH"
        from langchain_core.messages import AIMessage
        return {"next_agent": next_agent, "messages": [AIMessage(content=f"AI COO Error: {str(e)}")]}
        
    return {"next_agent": next_agent}

async def worker_node(state) -> dict:
    """
    A dynamic worker node that loads the persona of the 'next_agent' specified by the supervisor.
    """
    messages = state["messages"]
    agent_name = state.get("next_agent", "FINISH")
    
    if agent_name not in AGENT_PROMPTS:
        return {}
        
    logger.info(f"Agent '{agent_name}' processing task...")
    
    system_text = AGENT_PROMPTS[agent_name]
    full_messages = [SystemMessage(content=system_text)] + list(messages)
    
    mcp_tools = await mcp_client.get_tools()
    model_with_tools = create_model(tools=mcp_tools)
    
    try:
        response = await model_with_tools.ainvoke(full_messages)
        return {"messages": [response]}
    except Exception as e:
        logger.error(f"Execution failed for {agent_name}: {str(e)}")
        from langchain_core.messages import AIMessage
        return {"messages": [AIMessage(content=f"Worker Error ({agent_name}): {str(e)}")]}

def should_continue(state) -> str:
    """
    Decides if the worker node should transition to the tool node, or return to the supervisor.
    """
    messages = state["messages"]
    last_message = messages[-1]
    
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        logger.info(f"LLM requested {len(last_message.tool_calls)} tool call(s). Routing to tools node...")
        return "tools"
    
    return "end"

def supervisor_router(state) -> str:
    """
    Reads the supervisor's decision to route to the worker node or end.
    """
    agent = state.get("next_agent", "FINISH")
    if agent == "FINISH":
        return "end"
    return "worker"

async def tools_node(state) -> dict:
    """
    Executes tool calls generated by the worker agents against the MCP server.
    """
    messages = state["messages"]
    last_message = messages[-1]
    
    mcp_tools = await mcp_client.get_tools()
    mcp_tools_map = {tool.name: tool for tool in mcp_tools}
    
    async def execute_single_tool(tool_call):
        tool_name = tool_call["name"]
        tool_args = tool_call["args"]
        tool_id = tool_call["id"]
        
        logger.info(f"Executing tool: {tool_name}")
        
        if tool_name in mcp_tools_map:
            tool_obj = mcp_tools_map[tool_name]
            try:
                raw_result = await tool_obj.ainvoke(tool_args)
                logger.debug(f"Tool {tool_name} returned successfully.")
                
                # LangChain MCP adapters return a list of dicts. We need to extract the raw text
                # so the LLM doesn't get confused by the nested structure.
                if isinstance(raw_result, list):
                    result = "".join([item.get("text", "") for item in raw_result if isinstance(item, dict) and item.get("type") == "text"])
                else:
                    result = str(raw_result)
            except Exception as e:
                result = f"Error executing tool: {str(e)}"
                logger.error(result)
        else:
            result = f"Error: Tool '{tool_name}' not found on MCP Server."
            logger.error(result)
            
        return ToolMessage(content=str(result), tool_call_id=tool_id)

    tool_messages = await asyncio.gather(*(execute_single_tool(tc) for tc in last_message.tool_calls))
    
    return {"messages": list(tool_messages)}
